image:
  repository: 922718141496.dkr.ecr.eu-central-1.amazonaws.com/final-django
  tag: v1.14
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

config:
  DJANGO_SETTINGS_MODULE: "goit.settings"
  DEBUG: "true"
  ALLOWED_HOSTS: "*"
  POSTGRES_NAME: "mydb"
  POSTGRES_USER: "dbuser"
  POSTGRES_PASSWORD: "StrongPassword123!"
  POSTGRES_HOST: "mydb-rds-instance.cxec6oc8020n.eu-central-1.rds.amazonaws.com"
  POSTGRES_PORT: "5432"
