replicaCount: 2

image:
  repository: 922718141496.dkr.ecr.eu-central-1.amazonaws.com/lesson-7-django
  tag: "v1.7"

service:
  type: LoadBalancer
  port: 80

config:
  DJANGO_SETTINGS_MODULE: "goit.settings"
  DEBUG: "false"
  ALLOWED_HOSTS: "*"

resources: {}

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
