apiVersion: v1
kind: ConfigMap
metadata:
  name: web-django-app-config
  labels:
    app: web-django-app
data:
  DJANGO_SETTINGS_MODULE: "{{ .Values.config.DJANGO_SETTINGS_MODULE }}"
  DEBUG: "{{ .Values.config.DEBUG }}"
  ALLOWED_HOSTS: "{{ .Values.config.ALLOWED_HOSTS }}"
