apiVersion: v1
kind: ConfigMap
metadata:
  name: web-django-app-config
  labels:
    app: web-django-app
data:
  DJANGO_SETTINGS_MODULE: "goit.settings"
  DEBUG: "false"
  ALLOWED_HOSTS: "*"

  POSTGRES_HOST: "localhost"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
